[package]
name = "exact_diagonalization"
version = "0.1.0"
authors = ["Myeongseon Choi <key262yek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
ndarray = "0.13"
ndarray-linalg = "0.12"
num-complex = "0.4"
num = "0.4"
bitvec = "0.22"
fnv = "1.0"

[dev-dependencies]
criterion = "0.3.4"


[[bench]]
name = "bench_bit_iterator"
harness = false
